/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/finger.glb -o ./jsxComponents/finger.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/finger.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Feature_007} />
      <mesh geometry={nodes.node1.geometry} material={materials.Part__Feature001_006} />
    </group>
  )
}

useGLTF.preload('/finger.glb')
