/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/link5.glb -o ./jsxComponents/link5.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/link5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Feature_002_004_003} position={[0, -0.259, 0]} />
      <mesh geometry={nodes.node1.geometry} material={materials.Shell_001_001_003} position={[0, -0.259, 0]} />
      <mesh geometry={nodes.node2.geometry} material={materials.Shell001_001_001_003} position={[0, -0.259, 0]} />
    </group>
  )
}

useGLTF.preload('/link5.glb')
