/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/link7.glb -o ./jsxComponents/link7.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/link7.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Mirroring_004_001} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.node2.geometry} material={materials.Part__Mirroring002_004_001} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.node3.geometry} material={materials.Part__Mirroring003_004_001} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.node5.geometry} material={materials.Part__Mirroring005_004_001} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.node6.geometry} material={materials.Part__Mirroring006_004_001} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.node7.geometry} material={materials.Part__Mirroring007_004_001} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.node1.geometry} material={materials.Part__Mirroring001_004_002} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.node4.geometry} material={materials.Part__Mirroring004_004_002} position={[0, 0.052, 0]} rotation={[0, -Math.PI / 4, 0]} />
    </group>
  )
}

useGLTF.preload('/link7.glb')
