/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/link4.glb -o ./jsxComponents/link4.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/link4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Feature_002_003_001} position={[0, 0, -0.003]} />
      <mesh geometry={nodes.node1.geometry} material={materials.Part__Feature002_001_003_001} position={[0, 0, -0.003]} />
      <mesh geometry={nodes.node2.geometry} material={materials.Part__Feature003_001_003_001} position={[0, 0, -0.003]} />
      <mesh geometry={nodes.node3.geometry} material={materials.Part__Feature001_001_003_001} position={[0, 0, -0.003]} />
    </group>
  )
}

useGLTF.preload('/link4.glb')
