/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/link3.glb -o ./jsxComponents/link3.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/link3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node0_001.geometry} material={materials.Part__Feature_001_001_001_002} position={[0, -0.121, 0]} />
      <mesh geometry={nodes.node1.geometry} material={materials.Part__Feature001_010_001_002} position={[0, -0.121, 0]} />
      <mesh geometry={nodes.node2.geometry} material={materials.Part__Feature002_007_001_002} position={[0, -0.121, 0]} />
      <mesh geometry={nodes.node3.geometry} material={materials.Part__Feature003_004_001_002} position={[0, -0.121, 0]} />
    </group>
  )
}

useGLTF.preload('/link3.glb')
