/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/link1.glb -o ./jsxComponents/link1.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/link1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Feature_001} position={[0, -0.192, 0]} />
    </group>
  )
}

useGLTF.preload('/link1.glb')
