/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/link2.glb -o ./jsxComponents/link2.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/link2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Feature024} />
    </group>
  )
}

useGLTF.preload('/link2.glb')
