/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link6 from './link6.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link6);
  return [{type:'raw', geometry:nodes.link6.geometry, material: nodes.link6.material}]
  
}
useGLTF.preload(link6)