/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link3 from './link3.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link3);
  return [{type:'raw', geometry:nodes.link3.geometry, material: nodes.link3.material}]
  
}
useGLTF.preload(link3)