/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link4 from './link4.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link4);
  return [{type:'raw', geometry:nodes.link4.geometry, material: nodes.link4.material}]
  
}
useGLTF.preload(link4)