/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link1 from './link1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link1);
  return [{type:'raw', geometry:nodes.link1.geometry, material: nodes.link1.material}]
  
}
useGLTF.preload(link1)