/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link0 from './link0.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link0);
  return [{type:'raw', geometry:nodes.link0.geometry, material: nodes.link0.material}]
  
}
useGLTF.preload(link0)