/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link5 from './link5.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link5);
  return [{type:'raw', geometry:nodes.link5.geometry, material: nodes.link5.material}]
  
}
useGLTF.preload(link5)