/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link2 from './link2.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link2);
  return [{type:'raw', geometry:nodes.link2.geometry, material: nodes.link2.material}]
  
}
useGLTF.preload(link2)