/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link7 from './link7.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes } = useGLTF(link7);
  return [{type:'raw', geometry:nodes.link7.geometry, material: nodes.link7.material}]
  
}
useGLTF.preload(link7)