/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link1 from './link1.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {
  const { nodes, materials } = useGLTF(link1);
  return [{type:'raw', geometry: nodes.node0.geometry, material:materials.Part__Feature_001, position:[0, -0.19, 0]}]
}
useGLTF.preload(link1)