/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import link4 from './link4.glb';
import { useGLTF } from '@react-three/drei';
export default function Model(props) {

  const { nodes, materials } = useGLTF(link4);
  return [{type:'raw', geometry: nodes.node0.geometry,
  material:materials.Part__Feature_002_003_001, position:[0, 0, 0]},
  {type:'raw', geometry:nodes.node1.geometry,
  material:materials.Part__Feature002_001_003_001,position:[0, 0, 0]},
  {type:'raw', geometry:nodes.node2.geometry,
  material:materials.Part__Feature003_001_003_001, position:[0, 0, 0]},
  {type:'raw', geometry:nodes.node3.geometry,
  material:materials.Part__Feature001_001_003_001, position:[0, 0, 0]}]
}
useGLTF.preload(link4)